################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
A_os/SampleProcesses \
A_os/drivers/USB_Device/STM32F4/App \
A_os/drivers/USB_Device/STM32F4/Class/CDC \
A_os/drivers/USB_Device/STM32F4/Core \
A_os/drivers/USB_Device/STM32F4/Target \
A_os/drivers/USB_Device/STM32F7/App \
A_os/drivers/USB_Device/STM32F7/Class/CDC \
A_os/drivers/USB_Device/STM32F7/Core \
A_os/drivers/USB_Device/STM32F7/Target \
A_os/drivers/USB_Device/STM32G4xx/App \
A_os/drivers/USB_Device/STM32G4xx/Class/CDC \
A_os/drivers/USB_Device/STM32G4xx/Core \
A_os/drivers/USB_Device/STM32G4xx/Target \
A_os/drivers/USB_Device/STM32H563/App \
A_os/drivers/USB_Device/STM32H563/Class/CDC \
A_os/drivers/USB_Device/STM32H563/Core \
A_os/drivers/USB_Device/STM32H563/Target \
A_os/drivers/USB_Device/STM32H743/App \
A_os/drivers/USB_Device/STM32H743/Class/CDC \
A_os/drivers/USB_Device/STM32H743/Class/MIDI \
A_os/drivers/USB_Device/STM32H743/Core \
A_os/drivers/USB_Device/STM32H743/Target \
A_os/drivers/USB_Device/STM32U575/App \
A_os/drivers/USB_Device/STM32U575/Class/CDC \
A_os/drivers/USB_Device/STM32U575/Core \
A_os/drivers/USB_Device/STM32U575/Target \
A_os/drivers/USB_Device \
A_os/drivers/USB_Host/STM32H743/App \
A_os/drivers/USB_Host/STM32H743/Class/AUDIO \
A_os/drivers/USB_Host/STM32H743/Class/CDC \
A_os/drivers/USB_Host/STM32H743/Class/HID \
A_os/drivers/USB_Host/STM32H743/Class/MSC \
A_os/drivers/USB_Host/STM32H743/Class/MTP \
A_os/drivers/USB_Host/STM32H743/Core \
A_os/drivers/USB_Host/STM32H743/Target \
A_os/drivers/analog/adc \
A_os/drivers/analog/dac \
A_os/drivers/analog/i2s \
A_os/drivers/dmx512 \
A_os/drivers/fdcan \
A_os/drivers/gpio \
A_os/drivers/i2c/codecs \
A_os/drivers/i2c/e2pot \
A_os/drivers/i2c \
A_os/drivers/i2c/memories \
A_os/drivers/i2c/sensors/accgyro \
A_os/drivers/i2c/sensors/camera \
A_os/drivers/i2c/sensors/humidity \
A_os/drivers/i2c/sensors/pressure \
A_os/drivers/i2c/sensors/temperature \
A_os/drivers/i2c/sensors/tof \
A_os/drivers/qspi \
A_os/drivers/qspi/w25qxx \
A_os/drivers/rmii \
A_os/drivers/sdcard \
A_os/drivers/spi/NFC/PN5180 \
A_os/drivers/spi/NFC \
A_os/drivers/spi/dds \
A_os/drivers/spi/lcd \
A_os/drivers/spi/lcd/ili9341 \
A_os/drivers/spi/lcd/st7735 \
A_os/drivers/spi/nrf24l01 \
A_os/drivers/spi \
A_os/drivers/timers/dcc \
A_os/drivers/timers/dhtxx_am230x \
A_os/drivers/timers/encoder \
A_os/drivers/timers/periodic_timer \
A_os/drivers/timers/pwm \
A_os/drivers/timers/servo \
A_os/drivers/timers/stepper \
A_os/drivers/timers \
A_os/drivers/timers/ws2812 \
A_os/drivers/uart \
A_os/kernel \
A_os/kernel/flash_updater/STM32F446 \
A_os/kernel/flash_updater/STM32G4xx \
A_os/kernel/flash_updater/STM32H743_753 \
A_os/libraries/WiFi \
A_os/libraries/helix \
A_os/libraries/helix/real \
A_os/libraries/lwip2.2/App \
A_os/libraries/lwip2.2/LwIp/src/api \
A_os/libraries/lwip2.2/LwIp/src/apps/altcp_tls \
A_os/libraries/lwip2.2/LwIp/src/apps/http \
A_os/libraries/lwip2.2/LwIp/src/apps/lwiperf \
A_os/libraries/lwip2.2/LwIp/src/apps/mdns \
A_os/libraries/lwip2.2/LwIp/src/apps/mqtt \
A_os/libraries/lwip2.2/LwIp/src/apps/netbiosns \
A_os/libraries/lwip2.2/LwIp/src/apps/smtp \
A_os/libraries/lwip2.2/LwIp/src/apps/snmp \
A_os/libraries/lwip2.2/LwIp/src/apps/sntp \
A_os/libraries/lwip2.2/LwIp/src/apps/tftp \
A_os/libraries/lwip2.2/LwIp/src/core \
A_os/libraries/lwip2.2/LwIp/src/core/ipv4 \
A_os/libraries/lwip2.2/LwIp/src/core/ipv6 \
A_os/libraries/lwip2.2/LwIp/src/netif \
A_os/libraries/lwip2.2/LwIp/src/netif/ppp \
A_os/libraries/lwip2.2/LwIp/src/netif/ppp/polarssl \
A_os/libraries/lwip2.2/Target \
A_os/modules/dfplayer \
A_os/modules/fat \
A_os/modules/fat/option \
A_os/modules/hex_decoders \
A_os/modules/midi_decoder \
A_os/modules/modbus \
A_os/modules/mqtt_client \
A_os/modules/pid \
A_os/modules/serial_transfers \
A_os/modules/sound_engine/Effects \
A_os/modules/sound_engine/Generators/DrumSamples \
A_os/modules/sound_engine/Generators \
A_os/modules/sound_engine/OutStage \
A_os/modules/sound_engine/SFX \
A_os/modules/sound_engine \
Core/Src \
Core/Startup \
Drivers/STM32G4xx_HAL_Driver/Src \
Oven_Processes_211225-01 \

